name: deploy to wordpress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      # Clone the repo
      - uses: actions/checkout@main
      # PHP version
      - name: Setup PHP for min requirement
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      # Prepare the release
      - run: |
          ls
          php --version
          composer update
          composer install --no-dev
          npm install --production
          ls
      # Release to WordPress.org
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: user-export-with-their-meta-data
